version: '2'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./api.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: "redis:alpine"
